name: Integration tests

on:
  workflow_dispatch:
    workflow: "*"
  schedule:
    - cron:  '10 0 * * *'
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  integration_test:
    name: hs_${{ matrix.HYPERSPY_VERSION }}-ext_${{ matrix.EXTENSION_VERSION }}${{ matrix.LABEL }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        HYPERSPY_VERSION: ['release', 'RnP', 'RnM']
        EXTENSION_VERSION: ['release', 'dev']
        DEPENDENCIES_DEV: [false]
        DEPENDENCIES_PRE_RELEASE: [false]
        USE_MAMBA: [true]
        include:
          # test against upstream dev
          - DEPENDENCIES_DEV: true
            LABEL: -dependencies_dev
            HYPERSPY_VERSION: 'RnM'
            EXTENSION_VERSION: 'dev'
            # numba dev version is installed separately from numba/label/dev channel
            # others are installed as wheels from
            # https://pypi.anaconda.org/scipy-wheels-nightly/simple
            # add numpy when it is working again (import error)
            DEPENDENCIES: numba scipy scikit-image scikit-learn
            USE_MAMBA: false
          - DEPENDENCIES_PRE_RELEASE: true
            LABEL: -dependencies_pre_release
            HYPERSPY_VERSION: 'RnM'
            EXTENSION_VERSION: 'dev'
            DEPENDENCIES: matplotlib numba numpy scipy sympy h5py scikit-image scikit-learn
            USE_MAMBA: false

    env:
      MPLBACKEND: agg
      EXTENSION: kikuchipy lumispy pyxem
      TEST_DEPS: pytest pytest-xdist pytest-rerunfailures pytest-instafail
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@master
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          # use base environment, so that when using pip, this is from the
          # mambaforge distribution
          auto-activate-base: true
          activate-environment: ""

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Install dependencies development version
        if: ${{ matrix.DEPENDENCIES_DEV }}
        run: |
          mamba install -c numba/label/dev ${{ matrix.DEPENDENCIES }}
          pip install --upgrade --no-deps --pre -i \
            https://pypi.anaconda.org/scipy-wheels-nightly/simple \
            ${{ matrix.DEPENDENCIES }}

      - name: Install dependencies pre release version
        if: ${{ matrix.DEPENDENCIES_PRE_RELEASE }}
        run: |
          pip install --pre ${{ matrix.DEPENDENCIES }}

      - name: Install extensions and Test dependencies
        run: |
          if [ ${{ matrix.USE_MAMBA }} == true ] ; then
            mamba install hyperspy-base ${{ env.EXTENSION }} ${{ env.TEST_DEPS }}
          else
            pip install hyperspy ${{ env.EXTENSION }} ${{ env.TEST_DEPS }}
          fi

      - name: Conda list
        run: |
          conda list

      - name: Install HyperSpy RnP
        if: contains(matrix.HYPERSPY_VERSION, 'RnP')
        run: |
          pip install https://github.com/hyperspy/hyperspy/archive/RELEASE_next_patch.zip

      - name: Install HyperSpy RnM
        if: contains(matrix.HYPERSPY_VERSION, 'RnM')
        run: |
          pip install https://github.com/hyperspy/hyperspy/archive/RELEASE_next_minor.zip

      - name: Install Extension Dev
        if: contains(matrix.EXTENSION_VERSION, 'dev')
        run: |
          pip install https://github.com/lumispy/lumispy/archive/main.zip --no-deps
          pip install https://github.com/pyxem/kikuchipy/archive/main.zip --no-deps
          pip install https://github.com/pyxem/pyxem/archive/master.zip --no-deps

      - name: Clear conda and pip cache
        run: |
          conda clean --all
          pip cache purge

      - name: Run HyperSpy Test Suite
        run: |
          # Remove skipping test when new release include the packaging fix
          python -m pytest --pyargs hyperspy --reruns 3 -n 2 --instafail -k "not read_fail and not tvips_file_reader"

      - name: Run Kikuchipy Test Suite
        if: ${{ always() }}
        run: |
          # Remove skipping test when fix is included in a kikuchipy release
          python -m pytest --pyargs kikuchipy -k "not load_readonly"

      - name: Run LumiSpy Test Suite
        if: ${{ always() }}
        #if: contains(matrix.EXTENSION_VERSION, 'dev') # Tests only against development version, if a fix is not released yet.
        run: |
          python -m pytest --pyargs lumispy

      - name: Run Pyxem Test Suite
        if: ${{ always() }}
        run: |
          python -m pytest --pyargs pyxem -k "not learning_ncc_matrix"
